name: 'Your name here'
description: 'Provide a description here'
author: 'Lucas Nogueira <lucas@tauri.studio>'
inputs:
  uploadUrl:
    description: 'The URL for uploading assets to the release'
  tagName:
    description: 'The tag name of the release to create'
  releaseName:
    description: 'The name of the release to create'
  releaseBody:
    description: 'The body of the release to create'
  releaseDraft:
    description: 'Whether the release to create is a draft or not'
  prerelease:
    description: 'Whether the release to create is a prerelease or not'
  releaseCommitish:
    description: 'Any branch or commit SHA the Git tag is created from, unused if the Git tag already exists. Default: SHA of current commit'
  projectPath:
    description: 'path to the root of the project that will be built'
    default: '.'
  configPath:
    description: 'path to the tauri.conf.json file if you want a configuration different from the default one'
    default: 'tauri.conf.json'
  distPath:
    description: 'path to the distributable folder with your index.html and JS/CSS'
  iconPath:
    description: 'path to the PNG icon to use as app icon, relative to the projectPath'
  includeDebug:
    description: 'whether to include a debug build or not'
outputs:
  releaseId:
    description: 'The ID of the created release'
  releaseHtmlUrl:
    description: 'The URL users can navigate to in order to view the created release'
  releaseUploadUrl:
    description: 'The URL for uploading assets to the created release'
runs:
  using: 'node12'
  main: 'dist/main.js'
